server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 120.25.249.93 #指定redis所在的host
    password: Qq8981969.. #设置redis密码
    port: 6379
#  文件上传的大小限制：multipart类型
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      逻辑删除
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
#      主键自增
      id-type: auto
      table-prefix: sg_

oss:
  accessKey: DzwofQVACHviZl7CRk9KSIcSBlIm0Y7alBs42iuT
  secretKey: Q90p3rJZ1mPl27D0KNW62EcwN7hfOrCLtuiEc6tF
  bucket: sg-colablog
  domainName: http://rk54obks4.hn-bkt.clouddn.com/
